### PR TITLE
Estimation of Shelley header sizes

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by dcoutts** [comment]
Note that this will be much simpler as soon as the ledger updates to the latest cardano-crypto-class, so there's yet more incentive to do that.

**Comment by nc6** [comment]
There's a PR open to do that, but the changes in the crypto encoding break all of the serialisation tests, which are mostly just laborious to update.

**Comment by coot** [comment]
Requires both: #1429 and also https://github.com/input-output-hk/cardano-base/pull/115

**Comment by coot** [comment]
This is now done on top of #1429 (so it should be merged in order).

**Comment by coot** [comment]
There are no tests for the size bounds. They should be done in the same way as for byron: see [this module](https://github.com/input-output-hk/cardano-ledger/blob/master/cardano-ledger/test/Test/Cardano/Chain/Block/Size.hs).  Is it ok if I leave this for the ledger or formal team?

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Pull request merged**
