### PR TITLE
handwritten properties

### LINKED ISSUE #776: state Shelley ledger properties (for property tests)
Create a list of all the properties that need to hold for the Shelley ledger. We will then turn each of these into an issue for creating the property test.

### PR DESCRIPTION
**Pull request by JaredCorduan**
This is a work in progress list of properties for the Shelley ledger. We can add it to the latex spec when it's ready.

closes #776

### CODE REVIEW

**Comment by JaredCorduan** [comment]
> Agreed. OK for Circulation and Deposits to decrease?

yes! if I send you ADA, I pay a fee and circulation decreases. If I get a refund back, without registering anything new, deposits decreases.

**Comment by kevinhammond** [comment]
> > Agreed. OK for Circulation and Deposits to decrease?
> 
> yes! if I send you ADA, I pay a fee and circulation decreases. If I get a refund back, without registering anything new, deposits decreases.

Maybe be explicit about this? Can help with understanding :)

**Comment by kevinhammond** [comment]
From the Jormundgandr docs:

Transaction have fees that are defined by the blockchain settings and the following invariant hold:

∑Inputs=∑Outputs+fees
∑
I
n
p
u
t
s
=
∑
O
u
t
p
u
t
s
+
f
e
e
s

Transaction need to be authorized by each of the inputs in the transaction by their respective witness. In the most basic case, a witness is a cryptographic signature, but depending on the type of input can the type of witness vary.

**Comment by JaredCorduan** [comment]
> Consistency property for boundary case. Is there some property on minimal return of rewards too (was discussing this with Polina yesterday)? Will a live system always return some reward?

There are a couple ways a stake poor can fail to get any rewards, namely not meeting the pledge and also failing to produce blocks.

**Comment by JaredCorduan** [comment]
> "nearly" - be formal about this, e.g. define a term and show that it is satisfied. Is it still possible to make future progress from this state? Is there some kind of rebooting, or would the genesis key holders need to e.g. delegate? 

Sorry, yes, what was meant by "nearly" was what was explained next, namely that the named maps are empty and that the `cs` map has size `num-genesis-nodes`.  I will make this clearer.  

The system can indeed make progress from this state, it just requires folks registering stake keys and stake pools.

**Comment by JaredCorduan** [comment]
> the number of something times the Blocksmade mapping? Or a sum of something?

good catch! it is the sum of the values in the Blocksmade mapping. thanks!

**Comment by JaredCorduan** [comment]
> The Praos doc suggests that each transaction will produce at least k blocks. Am I misunderstanding something?

Would you be able to point me to a particular paragraph/page in the Praos spec?

**Comment by kevinhammond** [comment]
But if a pool meets those conditions will it receive a minimum guaranteed deposit?

**Comment by JaredCorduan** [comment]
> But if a pool meets those conditions will it receive a minimum guaranteed deposit?

I think it is still possible to get no rewards. You could pledge zero, have no stake, and get no delegations :) or if the monetary expansion is small, and there were little/no fees, due to rounding you could get nothing.

**Comment by kevinhammond** [comment]
Ok. That would come out through the types.

**Pull request merged**
