### PR TITLE
Gitignore .ghc.environment

### PR DESCRIPTION
**Pull request by mhuesch**
Used by `cabal v2-*` commands.

### CODE REVIEW

**Comment by mhuesch** [comment]
Not super important but it's annoying to have it appear in `git status`.

**Comment by intricate** [comment]
Just noticed that `stack.yaml.lock` is also in `.gitignore`. Any idea why? From what I understand this should be checked into source control as well.

**Comment by mhuesch** [comment]
Yeah, I'm not sure but haven't ever actually used `stack`'s lock file - have only ever checked in `stack.yaml` and assumed that e.g. `stack build` would do comparable things on different machines.

The [lock file docks](https://docs.haskellstack.org/en/stable/lock_files/) say that you can check the lockfile in for full determinism of builds, but maybe that's not proved to be necessary for us.

**Comment by dnadales** [comment]
> Just noticed that stack.yaml.lock is also in .gitignore. Any idea why? From what I understand this should be checked into source control as well.

Oh, I didn't know about this. From its name I just inferred it was a regular lock file.

**Comment by dnadales** [comment]
Ok, it seems we need to un-ignore the lock file 

https://docs.haskellstack.org/en/stable/lock_files/

**Comment by mhuesch** [comment]
Have we observed issues with the present way of building just from `stack.yaml`, though? I wonder if checking in the lock file introduces the possibility of the files being out of sync, which we might want to check in CI. Which would be some extra work that might not be necessary.

**Pull request merged**
