### PR TITLE
Errata in natural logarithm Taylor expansion 

### PR DESCRIPTION
**Pull request by csoroz**

### CODE REVIEW

**Comment by csoroz** [comment]
> 
> 
> good catch!
> please create a feature branch that only has this commit (and not the two merge commits) and do not merge the feature branch into your master before doing the PR
> If you do not know how to do this, I can also do another PR and use `git am` on your commit which will preserve it, including your name.

I'm not sure how to do that. I'm using the github web interface. The fork button always takes me to my old fork where I've updated the changes from iohk. Seems like it doesn't have the possibility of making a separate branch. Would it work if I delete my fork and create a new one? Or must I use the git command line necessarily?

If it's easy for you to resolve the PR it's OK.

**Comment by mgudemann** [comment]
> Would it work if I delete my fork and create a new one? Or must I use the git command line necessarily?

to be honest, I don't know. I haven't used the github interface directly myself. I created #418 which includes your commit verbatim, with you as the author. So we can just merge that one and close this here if you agree.

**Comment by csoroz** [comment]
> 
> 
> > Would it work if I delete my fork and create a new one? Or must I use the git command line necessarily?
> 
> to be honest, I don't know. I haven't used the github interface directly myself. I created #418 which includes your commit verbatim, with you as the author. So we can just merge that one and close this here if you agree.

Perfect. Thank you!

**Comment by mgudemann** [comment]
@csoroz thanks for spotting and fixing this!

**Pull request closed without merging**
