### PR TITLE
Change FromCBOR instance for PParams into applicative style

### PR DESCRIPTION
**Pull request by redxaxder**
This seems to help with compile times.

### CODE REVIEW

**Comment by JaredCorduan** [comment]
this fixes the OOM error when profiling on my local machine. :)

**Comment by mgudemann** [comment]
closes #1160

**Comment by edsko** [comment]
> this fixes the OOM error when profiling on my local machine. :)

Are you saying was was _ghc_ running out of memory, as opposed to the process when running?

**Comment by JaredCorduan** [comment]
> Are you saying was was _ghc_ running out of memory, as opposed to the process when running?

correct, the out of memory error was from running `stack build --profile`.

**Pull request merged**
