### PR TITLE
minor improvements and fixes to the mc-spec

### PR DESCRIPTION
**Pull request by WhatisRT**
Just some random improvements I found

### CODE REVIEW

**Comment by polinavino** [comment]
Looks good!

**Comment by JaredCorduan** [comment]
@WhatisRT you just need to sign the commit to get this through :)

**Comment by WhatisRT** [comment]
Alright, let's hope I got it this time

**Comment by JaredCorduan** [comment]
of the three commits, the first one is showing up as unsigned, but the other two look good

**Comment by polinavino** [comment]
Maybe make another PR with the same files if it's too annoying to sign the past commits? (I hope Jared has no objections to this)

**Comment by JaredCorduan** [comment]
> Maybe make another PR with the same files if it's too annoying to sign the past commits? (I hope Jared has no objections to this)

I think @WhatisRT figured out how to get it working, he just missed one.
This should do it, though:
```
git rebase --exec 'git commit --amend --no-edit -n -S' -i 5ffa1b15e707c0f95ab8ee095fffc9238302b61f
```

**Comment by WhatisRT** [comment]
Yeah, I have no idea how I missed that one. I double-checked everything and it should really work now

**Pull request merged**
