### PR TITLE
vertically aligned imports via stylish-haskell

### PR DESCRIPTION
**Pull request by JaredCorduan**
@redxaxder and I think that having vertically aligned imports will make diffs much easier to read and understand (because they are smaller).

What do y'all think?

### CODE REVIEW

**Comment by uroboros** [comment]
> @redxaxder and I think that having vertically aligned imports will make diffs much easier to read and understand (because they are smaller).
> 
> What do y'all think?



> @redxaxder and I think that having vertically aligned imports will make diffs much easier to read and understand (because they are smaller).
> 
> What do y'all think?

I'm for it.

**Comment by nc6** [comment]
Yep, solidly in favour. Although if we're suggesting formatting changes, what do you think about `ormolu`? I'm rather a fan, gives an actual unambiguous format, and helps with formatting things onto multi-lines.

**Comment by JaredCorduan** [comment]
> Yep, solidly in favour. Although if we're suggesting formatting changes, what do you think about `ormolu`? I'm rather a fan, gives an actual unambiguous format, and helps with formatting things onto multi-lines.

I am open to trying out ormolu!

**Comment by nc6** [comment]
Going to close this since people seemed happy with #1423

**Pull request closed without merging**
